___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Авторские права принадлежат Pierian Data Inc.</em></center>
<center><em>Для дополнительной информации посетите наш сайт <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Проверочный проект по линейной регрессии

Мы изучили построение признаков, кросс-валидацию и поиск по сетке. Пришло время проверить Ваши новые навыки. Добро пожаловать на проверочный проект по машинному обучению! В этом проекте у нас будут достаточно подробные пошаговые инструкции. Будущие проекты будут уже в более свободной форме. Мы начнём проект с финальной версии набора данных Ames Housing, с которым мы работали в разделе "построение признаков" этого курса. Цель этого проекта - создать модель линейной регрессии, обучить её на данных с поиском оптимальных значений параметров по сетке, и затем оценить модель на тестовом наборе данных.

---
---
---
## Выполните задания, написанные жирным шрифтом

**ЗАДАНИЕ: Выполните ячейки ниже для импорта библиотек и загрузки данных. Возможно в будущем Вам понадобятся дополнительные команды import от scikit-learn.**

### Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Данные

In [2]:
df = pd.read_csv("../DATA/AMES_Final_DF.csv")

In [3]:
df.head()

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,0,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,False,False,False,False,True,False,False,False,True,False
1,1,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,False,False,False,False,True,False,False,False,True,False
2,2,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,False,False,False,False,True,False,False,False,True,False
3,3,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,False,False,False,False,True,False,False,False,True,False
4,4,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,False,False,False,False,True,False,False,False,True,False

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Columns: 264 entries, Unnamed: 0 to Sale Condition_Partial
dtypes: bool(227), float64(11), int64(26)
memory usage: 1.5 MB

In [5]:
df.describe()

,Unnamed: 0,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
count,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,...,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000,2925.000000
mean,1462.000000,69.683099,10109.861538,6.091624,5.563761,1971.323761,1984.229060,100.318632,438.974359,49.790427,...,93.487521,47.210598,22.978462,2.596923,16.029402,2.083077,44.909744,6.216752,2007.791111,180815.537436
std,844.519094,21.344161,7785.509739,1.406386,1.112262,30.228826,20.857822,176.667803,439.426274,169.274143,...,126.146364,66.562829,64.093003,25.162589,56.131397,34.514231,472.237990,2.712550,1.317483,79951.696564
min,0.000000,0.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,12789.000000
25%,731.000000,60.000000,7438.000000,5.000000,5.000000,1954.000000,1965.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000,2007.000000,129500.000000
50%,1462.000000,70.000000,9430.000000,6.000000,5.000000,1973.000000,1993.000000,0.000000,370.000000,0.000000,...,0.000000,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,160000.000000
75%,2193.000000,80.000000,11526.000000,7.000000,6.000000,2000.000000,2004.000000,162.000000,734.000000,0.000000,...,168.000000,70.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,213500.000000
max,2924.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,2288.000000,1526.000000,...,1424.000000,742.000000,1012.000000,508.000000,576.000000,800.000000,15500.000000,12.000000,2010.000000,755000.000000

**ЗАДАНИЕ: Мы будем пытаться спрогнозировать значение колонки SalePrice. Разделите данные на две части - признаки X и целевая переменная y.**

In [6]:
X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

**ЗАДАНИЕ: С помощью scikit-learn разделите и X, и y на обучающий и тестовый наборы данных. Поскольку далее мы будем использовать поиск по сетке, то выделите под тестовые данные 10% от всех данных. Чтобы получить такое же разбиение данных, как и в нашем блокноте, можете использовать random_state = 101.**

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

**ЗАДАНИЕ: Признаки в этом наборе данных имеют различный масштаб и различные единицы измерения. Для оптимальной работы регрессии, выполните масштабирование признаков X. Обратите внимание на то, какие данные подавать на вход для .fit(), а какие данные на вход для .transform().**

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

**ЗАДАНИЕ: Мы будем использовать модель "Elastic Net". Создайте экземпляр модели ElasticNet в scikit-learn, используя параметры по умолчанию.**

In [9]:
from sklearn.linear_model import ElasticNet

elastic_model = ElasticNet()

**ЗАДАНИЕ: Модель Elastic Net работает с двумя основными параметрами - alpha и L1_ratio. Создайте словарь с набором различных значений этих параметров, для поиска по сетке. Вы можете выбрать различные значения параметров, но имейте ввиду, что Ваши результаты могут не совпасть с результатами в блокноте с решениями.**

In [10]:
parameter_grid = {'alpha':[0.1, 1, 5, 50, 100],
                  'l1_ratio':[.1, .5, .7, .95, .99, 1]}

**ЗАДАНИЕ: С помощью scikit-learn создайте объект GridSearchCV и запустите поиск по сетке для нахождения наилучших параметров модели, используя обучающие данные (предварительно смасштабированные). [Для некоторых комбинаций параметров Вы можете получить предупреждения (warnings).](https://stackoverflow.com/questions/20681864/lasso-on-sklearn-does-not-converge)**

In [23]:
from sklearn.model_selection import GridSearchCV

grid_model = GridSearchCV(estimator=elastic_model,
                          param_grid=parameter_grid,
                          scoring='neg_mean_squared_error',
                          cv=5,
                          n_jobs=-1)

In [24]:
import time
print('Lets GO!')
start = time.ctime()

grid_model.fit(X_train,y_train)

end = time.ctime()
print('all done!')
print('started', start)
print('finished', end)

Lets GO!

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.394e+11, tolerance: 1.308e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.878e+11, tolerance: 1.415e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.340e+11, tolerance: 1.355e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.853e+11, tolerance: 1.438e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.561e+11, tolerance: 1.346e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.308e+11, tolerance: 1.355e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.772e+11, tolerance: 1.308e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.538e+11, tolerance: 1.415e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.649e+11, tolerance: 1.438e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.690e+11, tolerance: 1.346e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.499e+11, tolerance: 1.355e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.522e+10, tolerance: 1.415e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.746e+10, tolerance: 1.308e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.299e+10, tolerance: 1.438e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.562e+11, tolerance: 1.346e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.401e+09, tolerance: 1.355e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.815e+09, tolerance: 1.415e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.606e+09, tolerance: 1.308e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.950e+09, tolerance: 1.438e+09
  model = cd_fast.enet_coordinate_descent(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.949e+09, tolerance: 1.346e+09
  model = cd_fast.enet_coordinate_descent(

all done!
started Mon Dec  8 16:27:56 2025
finished Mon Dec  8 16:28:02 2025

**ЗАДАНИЕ: Отобразите наилучшую комбинацию параметров для Вашей модели.**

In [19]:
grid_model.best_params_

{'alpha': 100, 'l1_ratio': 1}

**ЗАДАНИЕ: Оцените работу модели на тестовом наборе данных (предварительно смасштабированном) в 10%, которые модель ещё не видела. В блокноте с решениями мы получили MAE = $\$$14149 и RMSE = $\$$20532**

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

y_pred = grid_model.predict(X_test)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)

print(f'MAE: {MAE}')
print(f'MSE: {MSE}')
print(f'RMSE: {RMSE}')

print(f'Mean SalePrice: {np.mean(df["SalePrice"])}')

MAE: 14218.352383897889
MSE: 425166950.20210284
RMSE: 20619.576867678512
Mean SalePrice: 180815.53743589742

## LASSO

----

In [24]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
df = pd.read_csv("../DATA/AMES_Final_DF.csv")

X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
from sklearn.linear_model import LassoCV

lasso_cv_model = LassoCV(eps=0.1, n_alphas=100, cv=5)
lasso_cv_model.fit(X_train, y_train)

# оптимальное значение альфа (лямбда):
lasso_cv_model.alpha_

np.float64(6469.9565398050245)

In [32]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

y_pred = lasso_cv_model.predict(X_test)

MAE = mean_absolute_error(y_test,y_pred)
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)

print(f'MAE: {MAE:.2f}')
print(f'MSE: {MSE:.2f}')
print(f'RMSE: {RMSE:.2f}')

MAE: 20393.56
MSE: 805507182.68
RMSE: 28381.46

In [30]:
lasso_cv_model.coef_

array([    0.        ,     0.        ,  1085.77435373, 24289.73008695,
           0.        ,  2449.28764589,  3023.8742359 ,  3121.60425215,
        8501.32806021,     0.        ,    -0.        ,  7510.73675097,
        3204.83128191,     0.        ,    -0.        , 24168.11828629,
           0.        ,    -0.        ,     0.        ,     0.        ,
          -0.        ,    -0.        ,     0.        ,   253.5251242 ,
           0.        ,     0.        ,  5627.71062949,     0.        ,
           0.        ,    -0.        ,     0.        ,     0.        ,
           0.        ,    -0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,     0.        ,    -0.        ,
          -0.        ,     0.        ,    -0.        ,    -0.        ,
          -0.        ,     0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,     0.        ,     0.        ,     0.        ,
          -0.        ,     0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,     0.        ,     0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,     0.        ,    -0.        ,     0.        ,
          -0.        ,     0.        ,    -0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,    -0.        ,
          -0.        ,     0.        ,  2816.99357092,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
         186.89789708,     0.        ,     0.        ,    -0.        ,
           0.        ,     0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,    -0.        ,
          -0.        ,     0.        ,     0.        ,    -0.        ,
          -0.        ,     0.        ,    -0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,    -0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,    -0.        ,     0.        ,     0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,    -0.        ,     0.        ,     0.        ,
           0.        ,    -0.        ,    -0.        ,    -0.        ,
          -0.        ,     0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,    -0.        ,    -0.        ,
          -0.        ,     0.        ,     0.        ,     0.        ,
          -0.        ,     0.        ,    -0.        ,     0.        ,
          -0.        ,     0.        ,     0.        ,    -0.        ,
           0.        ,    -0.        ,    -0.        ,    -0.        ,
          -0.        ,     0.        ,    -0.        ,     0.        ,
       -1637.00091411,    -0.        ,     0.        ,    -0.        ,
           0.        ,    -0.        ,   299.91667196,     0.        ,
           0.        ,    -0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,     0.        ,  2501.2536027 ,    -0.        ,
          -0.        ,    -0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,    -0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,     0.        ,    -0.        ,
        -613.73422591,    -0.        ,    -0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,     0.        ,
          -0.        ,     0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,    -0.        ,    -0.        ,
           0.        ,    -0.        ,     0.        ,    -0.        ,
           0.        ,    -0.        ,     0.        ,    -0.        ,
           0.        ,    -0.        ,     0.        ,    -0.        ,
          -0.        ,    -0.        ,  2825.67591132,     0.        ,
          -0.        ,    -0.        ,    -0.        ,    -0.        ,
          -0.        ,    -0.        ,     0.        ])

---
### Ridge

In [43]:
from sklearn.linear_model import RidgeCV

ridge_cv_model = RidgeCV(alphas=[.1,.5,1,5,9,10,11,20,30], scoring='neg_mean_absolute_error')
ridge_cv_model.fit(X_train, y_train)

y_pred = ridge_cv_model.predict(X_test)

MAE = mean_absolute_error(y_test,y_pred)
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)

print(ridge_cv_model.alpha_)
print(f'MAE: {MAE}')
print(f'MSE: {MSE}')
print(f'RMSE: {RMSE}')

30.0
MAE: 14330.96199491533
MSE: 433615900.6041918
RMSE: 20823.445934911728

---
### Simple Linear Regression

In [44]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
df = pd.read_csv("../DATA/AMES_Final_DF.csv")

X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

In [47]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [48]:
from sklearn.linear_model import LinearRegression

linear_reg_model = LinearRegression()
linear_reg_model.fit(X_train, y_train)

y_pred = linear_reg_model.predict(X_test)

MAE = mean_absolute_error(y_test,y_pred)
MSE = mean_squared_error(y_test,y_pred)
RMSE = np.sqrt(MSE)

print(ridge_cv_model.alpha_)
print(f'MAE: {MAE}')
print(f'MSE: {MSE}')
print(f'RMSE: {RMSE}')

30.0
MAE: 15778.494118233935
MSE: 586495011.2218784
RMSE: 24217.659078075205